<?php

namespace App\Modules\Admin\User\Requests;

use App\Services\Requests\ApiRequest;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;

class UserRequest extends ApiRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return Auth::user()->canDo(['super_admin', 'users_access']);
    }

    protected function getValidatorInstance()
    {
        $validator = parent::getValidatorInstance(); // TODO: Change the autogenerated stub

        $validator->sometimes('password', ['required', 'confirmed'], function ($input) {
            if (!empty($input->password) || (empty($input->password) && ($this->route()->getName() != "api.users.update"))) {
                return true;
            }
            return false;
        });

        return $validator;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'firstname'=>'required',
            'lastname'=>'required',
            'email'=>'required',
            'phone'=>'required',
            'role_id'=>'required'
        ];
    }
}
